### ISSUE TITLE
Support for free text search over records

### ISSUE THREAD

**Issue by mike-hogan** [cozemble/monorepo#14]
When I am viewing a list of records, let's say a list of Customers, I want to be able to filter the list by free text search.

So if I type in "mike" into the search bar, all Customers containing the string "mike" anywhere in their schema are shown

**Comment by samsoft00** [comment]
This is interesting, so, the structure will look like right?

```graphql
enum FilterBy {
  NAME,
  AGE,
  CREATED_AT,
}
query {
    search: String!,
     filter_by: [] //fetch the model keys as enum. e.g name,
}
```

**Comment by mike-hogan** [comment]
I didn't intended this to be about typescript interfaces @samsoft00 .  I mean the data editor, which is model driven, will "just know" how to do free text search against the model it is viewing.  It knows all the properties in the model, so it can dynamically generate a query to implement the search.

That would be enough to get going.

Keeping an index or using a search engine is an optional improvement that we can make should the need arise.

You had extra thoughts around the typescript interface?

**Comment by mike-hogan** [comment]
Not doing this using right now, as we have moved away from the idea of a custom sql schema for each tenant, back to generic models and records.  First step is to see if postgres jsonb querying does all we need.

**Comment by mike-hogan** [comment]
What I meant was not doing this (gql) approach to free text search.  But we still need the feature.  It's done now using a trigger that "textifies" the record, and added support for q=xxxx to the records endpoint
