### ISSUE TITLE
Support multiline text

### ISSUE THREAD

**Issue by mike-hogan** [cozemble/monorepo#16]
Let's say we have a Booking record type, and it has a notes field, that notes field needs to support multiline text.  Right now pressing Enter in a text field submits the data.

**Comment by samsoft00** [comment]
Is this going to support adding some special characters within the text? like HTML tags?

**Comment by mike-hogan** [comment]
I don't think so @samsoft00 .  I think explicit support for rich text editing should be done as a custom cell type.  I have opened #35 accordingly

**Comment by mike-hogan** [comment]
Done
